---
ID: "2ac1f2fc-88df-471c-b57a-5e75edfc877f"
Parent: "a397b4b8-fc82-4dba-b88e-759d1b7d4bec"
Template: "efafbbf5-01a0-46d3-9f7b-e71763e7f221"
Path: /sitecore/content/Brand A/Brand A Corporate Website/Settings/Social Media Groups/Default
BranchID: "4ddbdd69-8a15-4520-bed8-f7553139586b"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{E35BE623-2154-4300-A80E-F054B26B76C5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230813T233756Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b0b2303e-98c5-412a-9f2b-eef8f2d0c80e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230813T233756Z
